version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build: 
    docker: 
      - image: circleci/node:12.18
      - image: circleci/postgres:9.6.2-alpine
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD # context / project UI env-var reference
        environment:
          POSTGRES_USER: example
          POSTGRES_DB: sneakerdb
          POSTGRES_PASSWORD: example
    steps:
      - checkout

      - run: cd api && npm ci
      - run: cd api && npm start
      - run: cd api && npm test

   
      - setup_remote_docker
      
      - run: |
          cd api
          TAG="0.1.${CIRCLE_BUILD_NUM}"
          docker build -t andreske02/compare-sneaker-api:$TAG .
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
          docker push andreske02/compare-sneaker-api:$TAG